[package]
name = "glittr-core"
description = "Glittr protocol implementation"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
bitcoin = "0.32.3"
bitcoincore-rpc = "0.19.0"
borsh = "1.5.1"
borsh-derive = "1.5.1"
config = "0.14.0"
env_logger = "0.11.5"
lazy_static = "1.5.0"
log = "0.4.22"
rocksdb = "0.22.0"
serde = "1.0.210"
tokio = "1.40.0"

[[bin]]
name = "glittr"
path = "src/bin/main.rs"

[lib]
name = "glittr"
path = "src/lib.rs"

[dev-dependencies]
mockcore = "0.0.0"
